using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Balynn.Math.PerformanceTests.Fraction")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("Balynn.Math.PerformanceTests.Fraction")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("4bcb405c-09f5-4320-812d-90d2f6d0da01")]